# --- Inventory for Kubeadm Cluster ---

[master]
# Using the output 'master_public_ip'
k8s-master ansible_host=16.171.239.35

[workers]
# Using the output 'worker_public_ips'
k8s-worker-0 ansible_host=56.228.82.151
k8s-worker-1 ansible_host=13.61.151.248

[all:vars]
# User for Ubuntu AMI (ami-02e70da87e10e9324)
ansible_user=ubuntu
# Private key matching your 'daily-key' resource
ansible_ssh_private_key_file=~/.ssh/daily-key
# Standard skip for new AWS instances host keys
ansible_ssh_common_args='-o StrictHostKeyChecking=no'